In [1]:
import numpy as np
import sys

sys.path.append("../src/")
from utils import *

In [2]:
d = 3
mu = np.random.random(d)
Sigma = np.identity(d) + 0.5
assert np.linalg.det(Sigma) != 0

In [3]:
x = np.array([1, 2, 3])
multivariate_normal_density(x, mu, Sigma)

0.0012884587189913657

In [4]:
multivariate_normal_density(x, mu, Sigma, log=True)

-6.6543085664205

In [5]:
x = np.zeros((4, d))
x[0] = np.array([1, 2, 3])
x[1:] = np.random.random((3, d))

In [6]:
multivariate_normal_density(x, mu, Sigma)

array([0.00128846, 0.0251533 , 0.03672992, 0.02550721])

In [7]:
multivariate_normal_density(x, mu, Sigma, log=True)

array([-6.65430857, -3.68276626, -3.30416372, -3.66879425])

In [8]:
Theta = np.random.random(2)
Sigma = np.random.random()
Theta_Sigma = concatenate_Theta_Sigma_i(Theta, Sigma)
Theta, Sigma, Theta_Sigma

(array([0.69555486, 0.98727274]),
 0.1683987808698827,
 array([0.69555486, 0.98727274, 0.16839878]))

In [9]:
retrieve_Theta_Sigma_i(Theta_Sigma)

(array([0.69555486, 0.98727274]), 0.1683987808698827)