In [1]:
import numpy as np
import sys

sys.path.append("../src/")
from utils import *

In [2]:
d = 3
mu = np.random.random(d)
Sigma = np.identity(d) + 0.5
assert np.linalg.det(Sigma) != 0

In [3]:
x = np.array([1, 2, 3])
multivariate_normal_density(x, mu, Sigma)

0.0012884587189913657

In [4]:
multivariate_normal_density(x, mu, Sigma, log=True)

-6.6543085664205

In [5]:
x = np.zeros((4, d))
x[0] = np.array([1, 2, 3])
x[1:] = np.random.random((3, d))

In [6]:
multivariate_normal_density(x, mu, Sigma)

array([0.00128846, 0.0251533 , 0.03672992, 0.02550721])

In [7]:
multivariate_normal_density(x, mu, Sigma, log=True)

array([-6.65430857, -3.68276626, -3.30416372, -3.66879425])

In [8]:
Theta = np.random.random(2)
Sigma = np.random.random()
Theta_Sigma = concatenate_Theta_Sigma_i(Theta, Sigma)
Theta, Sigma, Theta_Sigma

(array([0.69555486, 0.98727274]),
 0.1683987808698827,
 array([0.69555486, 0.98727274, 0.16839878]))

In [9]:
retrieve_Theta_Sigma_i(Theta_Sigma)

(array([0.69555486, 0.98727274]), 0.1683987808698827)

In [6]:
import numpy as np

T_ref = np.array([2, 1, 3, 5, 4, 6])
Ti = np.array([1, 2, 4, 5])
Yi = np.array([10, 20, 40, 50])

Y_ref = np.zeros_like(T_ref)
indices_in_Ti = np.where(np.isin(Ti, T_ref))[0]
Y_ref[indices_in_Ti] = Yi[np.searchsorted(Ti, T_ref[indices_in_Ti], sorter=np.arange(len(Ti)))]

print("T_ref :", T_ref)
print("Y_ref :", Y_ref)

T_ref : [2 1 3 5 4 6]
Y_ref : [20 10 40 50  0  0]


In [9]:
Y = [np.random.randint(0, 10, size=5), np.random.randint(0, 10, size=10), np.random.randint(0, 10, size=7)]
Y

[array([2, 7, 1, 8, 5]),
 array([8, 1, 7, 0, 7, 1, 8, 9, 3, 2]),
 array([5, 1, 8, 5, 3, 3, 9])]

In [10]:
T = [np.random.randint(0, 10, size=5), np.random.randint(0, 10, size=10), np.random.randint(0, 10, size=7)]
T

[array([0, 7, 7, 3, 8]),
 array([6, 5, 1, 8, 9, 8, 5, 5, 6, 7]),
 array([4, 0, 9, 1, 1, 0, 9])]

In [12]:
common_T = np.arange(0, 10)
n_common_T = 10
common_T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
n_individuals = len(Y)
T_masks = np.zeros((n_individuals, n_common_T))
Y_normalized = np.zeros((n_individuals, n_common_T))
for i in range(n_individuals):
    mask = np.isin(common_T, T[i])
    T_masks[i] = mask
    Yi_normalized = np.zeros(n_common_T)
    idx_Ti = np.where(np.isin(T[i], common_T))[0]
    Yi_normalized[idx_Ti] = Y[i][np.searchsorted(T[i], common_T[idx_Ti], sorter=np.arange(len(T[i])))]
    Y_normalized[i] = Yi_normalized

ValueError: could not broadcast input array from shape (10,) into shape (3,)