In [1]:
import numpy as np
import sys

sys.path.append("../src/")
from utils import *

In [2]:
d = 3
mu = np.random.random(d)
Sigma = np.identity(d) + 0.5
assert np.linalg.det(Sigma) != 0

In [3]:
x = np.array([1, 2, 3])
multivariate_normal_density(x, mu, Sigma)

0.0012884587189913657

In [4]:
multivariate_normal_density(x, mu, Sigma, log=True)

-6.6543085664205

In [5]:
x = np.zeros((4, d))
x[0] = np.array([1, 2, 3])
x[1:] = np.random.random((3, d))

In [6]:
multivariate_normal_density(x, mu, Sigma)

array([0.00128846, 0.0251533 , 0.03672992, 0.02550721])

In [7]:
multivariate_normal_density(x, mu, Sigma, log=True)

array([-6.65430857, -3.68276626, -3.30416372, -3.66879425])

In [42]:
Theta = np.random.random(2)
Sigma = np.random.random()
Theta_Sigma = concatenate_Theta_Sigma_i(Theta, Sigma)
Theta, Sigma, Theta_Sigma

(array([0.01189773, 0.59986137]),
 0.8086928432514426,
 array([0.01189773, 0.59986137, 0.80869284]))

In [9]:
retrieve_Theta_Sigma_i(Theta_Sigma)

(array([0.69555486, 0.98727274]), 0.1683987808698827)

In [40]:
T = np.random.randint(0, 10, size=5)

In [43]:
compute_inv_Psi_individual_i(
    ExponentiatedQuadraticKernel,
    Theta,
    Sigma,
    T
    )

(array([[8.08834399e-01, 3.12952597e-14, 5.24490785e-10, 5.45840726e-07,
         1.41556036e-04],
        [3.12952597e-14, 8.08834399e-01, 3.52746554e-05, 2.66787986e-26,
         3.12952597e-14],
        [5.24490785e-10, 3.52746554e-05, 8.08834399e-01, 1.15954612e-19,
         5.24490785e-10],
        [5.45840726e-07, 2.66787986e-26, 1.15954612e-19, 8.08834399e-01,
         5.45840726e-07],
        [1.41556036e-04, 3.12952597e-14, 5.24490785e-10, 5.45840726e-07,
         8.08834399e-01]]),
 array([[ 1.23634706e+00, -1.26793351e-14, -8.01572179e-10,
         -8.34201005e-07, -2.16376046e-04],
        [-1.28226697e-14,  1.23634702e+00, -5.39192141e-05,
         -3.14318622e-17, -1.23747211e-14],
        [-8.01572179e-10, -5.39192141e-05,  1.23634702e+00,
          1.32988268e-15, -8.01572164e-10],
        [-8.34201005e-07, -6.40977346e-17,  1.26300284e-15,
          1.23634702e+00, -8.34201005e-07],
        [-2.16376046e-04, -1.27786251e-14, -8.01572137e-10,
         -8.34201005e-07,  

In [49]:
mask = np.random.randint(0, 2, size=5)
mask

array([0, 0, 0, 1, 1])

In [50]:
compute_inv_Psi_individual_i(
    ExponentiatedQuadraticKernel,
    Theta,
    Sigma,
    T,
    mask
    )

(array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 8.08834399e-01,
         5.45840726e-07],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.45840726e-07,
         8.08834399e-01]]),
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.23634702e+00, -8.34347000e-07],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.34347000e-07,  